{{- if .Values.workloadNetworkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sonarqube-workload-ingress
spec:
  podSelector:
    matchLabels:
      release: sonarqube
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector: {}
    - namespaceSelector:
        matchLabels:
          platform-access: 'true'
{{- end }}
